// ═══════════════════════════════════════
// NexControl — Slots Premium Mock Data
// Estruturado para ser substituído por dados dinâmicos
// ═══════════════════════════════════════

export const PROVIDERS = [
  { id: 'all', label: 'Todos' },
  { id: 'pg', label: 'PG' },
  { id: 'pp', label: 'PP' },
  { id: 'wg', label: 'WG' },
  { id: 'mg', label: 'MG' },
  { id: 'jili', label: 'JILI' },
  { id: 'jdb', label: 'JDB' },
  { id: 'fc', label: 'FC' },
  { id: 'pescaria', label: 'Pescaria' },
]

export const SLOTS = [
  { id: 1, name: 'Fortune Tiger', provider: 'pg', rating: 5, performance: 'alta', tags: ['Popular', 'Rápido'], image: null },
  { id: 2, name: 'Fortune Ox', provider: 'pg', rating: 4, performance: 'alta', tags: ['Clássico', 'Estável'], image: null },
  { id: 3, name: 'Fortune Mouse', provider: 'pg', rating: 4, performance: 'media', tags: ['Rápido'], image: null },
  { id: 4, name: 'Fortune Rabbit', provider: 'pg', rating: 3, performance: 'media', tags: ['Novo'], image: null },
  { id: 5, name: 'Fortune Dragon', provider: 'pg', rating: 5, performance: 'alta', tags: ['Premium', 'Popular'], image: null },
  { id: 6, name: 'Ganesha Gold', provider: 'pg', rating: 4, performance: 'alta', tags: ['Estável', 'Clássico'], image: null },
  { id: 7, name: 'Wild Bandito', provider: 'pg', rating: 4, performance: 'media', tags: ['Ação'], image: null },
  { id: 8, name: 'Mahjong Ways', provider: 'pg', rating: 5, performance: 'alta', tags: ['Cartas', 'Popular'], image: null },
  { id: 9, name: 'Bikini Paradise', provider: 'pg', rating: 3, performance: 'media', tags: ['Casual'], image: null },
  { id: 10, name: 'Double Fortune', provider: 'pg', rating: 4, performance: 'alta', tags: ['Clássico'], image: null },
  { id: 11, name: 'Starlight Princess', provider: 'pp', rating: 5, performance: 'alta', tags: ['Premium', 'Popular'], image: null },
  { id: 12, name: 'Sweet Bonanza', provider: 'pp', rating: 5, performance: 'alta', tags: ['Clássico', 'Rápido'], image: null },
  { id: 13, name: 'Gates of Olympus', provider: 'pp', rating: 5, performance: 'alta', tags: ['Premium', 'Popular'], image: null },
  { id: 14, name: 'Sugar Rush', provider: 'pp', rating: 4, performance: 'media', tags: ['Casual', 'Rápido'], image: null },
  { id: 15, name: 'Big Bass Bonanza', provider: 'pp', rating: 4, performance: 'alta', tags: ['Pescaria', 'Popular'], image: null },
  { id: 16, name: 'Wolf Gold', provider: 'pp', rating: 4, performance: 'media', tags: ['Clássico'], image: null },
  { id: 17, name: 'Blazing Wilds', provider: 'wg', rating: 4, performance: 'alta', tags: ['Ação', 'Rápido'], image: null },
  { id: 18, name: 'Lucky Drums', provider: 'wg', rating: 3, performance: 'media', tags: ['Casual'], image: null },
  { id: 19, name: 'Wild Ape', provider: 'wg', rating: 4, performance: 'alta', tags: ['Ação'], image: null },
  { id: 20, name: 'Golden Empire', provider: 'wg', rating: 5, performance: 'alta', tags: ['Premium'], image: null },
  { id: 21, name: 'Mystic Fortune', provider: 'mg', rating: 4, performance: 'media', tags: ['Cartas'], image: null },
  { id: 22, name: 'Dragon Hatch', provider: 'mg', rating: 4, performance: 'alta', tags: ['Popular', 'Ação'], image: null },
  { id: 23, name: 'Treasure Quest', provider: 'mg', rating: 3, performance: 'media', tags: ['Aventura'], image: null },
  { id: 24, name: 'Money Coming', provider: 'jili', rating: 5, performance: 'alta', tags: ['Popular', 'Rápido'], image: null },
  { id: 25, name: 'Super Ace', provider: 'jili', rating: 5, performance: 'alta', tags: ['Premium', 'Cartas'], image: null },
  { id: 26, name: 'Boxing King', provider: 'jili', rating: 4, performance: 'media', tags: ['Ação'], image: null },
  { id: 27, name: 'Crazy Hunter', provider: 'jili', rating: 4, performance: 'alta', tags: ['Rápido'], image: null },
  { id: 28, name: 'Fishing War', provider: 'jdb', rating: 4, performance: 'alta', tags: ['Pescaria', 'Ação'], image: null },
  { id: 29, name: 'Cai Shen', provider: 'jdb', rating: 4, performance: 'media', tags: ['Clássico'], image: null },
  { id: 30, name: 'Birds Party', provider: 'jdb', rating: 3, performance: 'media', tags: ['Casual'], image: null },
  { id: 31, name: 'Mega Fishing', provider: 'fc', rating: 5, performance: 'alta', tags: ['Pescaria', 'Premium'], image: null },
  { id: 32, name: 'Golden Toad', provider: 'fc', rating: 4, performance: 'alta', tags: ['Clássico'], image: null },
  { id: 33, name: 'Monkey King', provider: 'fc', rating: 4, performance: 'media', tags: ['Ação', 'Aventura'], image: null },
  { id: 34, name: 'Ocean King', provider: 'pescaria', rating: 5, performance: 'alta', tags: ['Pescaria', 'Premium'], image: null },
  { id: 35, name: 'Fishing Joy', provider: 'pescaria', rating: 4, performance: 'alta', tags: ['Pescaria', 'Popular'], image: null },
  { id: 36, name: 'Happy Fishing', provider: 'pescaria', rating: 3, performance: 'media', tags: ['Pescaria', 'Casual'], image: null },
]
